apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-service
spec:
  ports:
    - name: http
      targetPort: {{ .Values.service.port }}
      port: {{ .Values.service.port }}
  selector:
    app: {{ include "helm.name" . }}
